export const navitems = [ // this is the menu items like home , company, about, carrier etc 
    { Id: 1, Name: "Home", color: "#4b5320", ScreenName: 'Home' },
    { Id: 2, Name: "Company", color: "#4b5320", ScreenName: "Company" },
    { Id: 3, Name: "About Us", color: "#7e8c36", ScreenName: "About" },
    { Id: 4, Name: "Our Success Story", color: "#7e8c36" , ScreenName: "OurScreenStory"  },
    { Id: 5, Name: "Director's Speech", color: "#7e8c36" , ScreenName: "Direct" },
    { Id: 6, Name: "Our Team", color: "#7e8c36" , ScreenName: "Team"  },
    { Id: 7, Name: "Our Strength", color: "#7e8c36" , ScreenName: "ourstrength"  },
    { Id: 8, Name: "Request Quote", color: "#7e8c36" , ScreenName: "requestQuet"  },
    { Id: 9, Name: "Services ", color: "#4b5320" , ScreenName: ""  },
    { Id: 10, Name: "Education", color: "#7e8c36" , ScreenName: "education"  },
    { Id: 11, Name: "Industries", color: "#7e8c36" , ScreenName: "indSer"  },
    { Id: 12, Name: "Corporate", color: "#7e8c36" , ScreenName: "corp"  },
    { Id: 13, Name: "Call Center", color: "#7e8c36" , ScreenName: "call"  },
    { Id: 14, Name: "Hospital", color: "#7e8c36" , ScreenName: "host"  },
    { Id: 15, Name: "Websites", color: "#7e8c36" , ScreenName: "websit"  },
    { Id: 16, Name: "Industries", color: "#4b5320" , ScreenName: ""  },
    { Id: 17, Name: "Proximity cards", color: "#7e8c36" , ScreenName: "proximity"  },
    { Id: 18, Name: "Attendance Mac", color: "#7e8c36" , ScreenName: "attend"  },
    { Id: 19, Name: "Barcode Reader", color: "#7e8c36" , ScreenName: "barcode"  },
    { Id: 20, Name: "IP Boards", color: "#7e8c36" , ScreenName: "ipbord"  },
    { Id: 21, Name: "Softwares", color: "#7e8c36" , ScreenName: "soft"  },
    { Id: 22, Name: "Client", color: "#4b5320" , ScreenName: "clit"},
    { Id: 23, Name: "Download", color: "#4b5320" , ScreenName: ""  },
    { Id: 24, Name: "Gallary", color: "#4b5320" , ScreenName: "galary"  },
    { Id: 25, Name: "Picture", color: "#7e8c36" , ScreenName: "About"  },
    { Id: 26, Name: "Video", color: "#7e8c36" , ScreenName: "About"  },
    { Id: 27, Name: "Media & News", color: "#7e8c36" , ScreenName: "media"},
    { Id: 28, Name: "Contact", color: "#4b5320" , ScreenName: "contact"  },
     
];